### ISSUE TITLE
@return being inserted even without a return statement in the function

### ISSUE THREAD

**Issue by Multiply** [oct8cat/sublime-phpdox#2]
There shouldn't be any `@return` statement if there's no return in the actual function.

**Comment by oct8cat** [comment]
Code sniffer _requires_ `@return` tag even if the function haven't returned value (`@return void` is used in this case). So there are several ways to resolve `@return` tag:
1. Hardcode to `@return void` and allow to programmer to define the returned value type and description.
2. Search the function's body for `return` statements:
   - If no returned values found - `@return void`
   - If one returned value found - try to resolve the returned value's type.

The question is: What if the fuction have more than one `return` statements? Try to resolve latest found value's type, or use `@return mixed`, or something else?

**Comment by Multiply** [comment]
According to many standards, `@return void` is essentially wrong, as PHP will always return null, if nothing is returned.
http://stackoverflow.com/questions/2061550/phpdoc-return-void-necessary and http://code.garyjones.co.uk/why-return-void-is-wrong/ are good for reference.

**Comment by Multiply** [comment]
There's no way to properly detect _what_ it returns, if it's calling another function. Not until you parse all your code. I'd say leave it be. (mixed)
