### ISSUE TITLE
TypeError: 'NoneType' object is unsubscriptable

### ISSUE THREAD

**Issue by Ultrabenosaurus** [oct8cat/sublime-phpdox#4]
Whenever I run this plugin I get the following error:

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 362, in run_
  File ".\PhpDox.py", line 68, in run
  File ".\PhpDox.py", line 79, in process_line
TypeError: 'NoneType' object is unsubscriptable
```

Line 68: `snippet = self.process_line(v.substr(line))`
Line 79: `for p_name, p_string in self.settings.get('phpdox')['patterns'].items():`

Installed through Package Control.
Sublime build Dev 2220

**Comment by oct8cat** [comment]
Please, check [this discussion](https://github.com/oct8cat/sublime-phpdox/issues/3#issuecomment-8792843)

**Comment by Ultrabenosaurus** [comment]
I won't be able to check my Python version until Friday now, but I have not installed a custom version of Python on that particular machine. Its running Windows 7 Professional 64bit. Unlike broldo I have not moved, renamed or otherwise modified any of my Sublime folders or settings outside of installing plugins and redefining a few keymaps (in the users file, not the default or plugin-specific).

**Comment by Ultrabenosaurus** [comment]
Output of `view.settings().get('phpdox')`:

```
>>> view.settings().get('phpdox')
{'patterns': {'function': u'^\\s*(?P<access>public|protected|private|)\\s*(?P<static>static|)\\s*function\\s+(?P<name>\\w+)\\s*\\((?P<params>.*)\\).*', 'interface': u'^\\s*interface\\s+(?P<name_interface>\\w+)\\s*(extends|)\\s*(?P<name_parent>\\w+|\\s*).*', 'variable': u'^\\s*(?P<access>public|protected|private|var)\\s*(?P<static>static|)\\s*(?P<name>\\$\\w+)\\s*(\\s*=\\s*|)(?P<value>.*|);.*', 'class': u'^\\s*(?P<abstract>abstract|)\\s*class\\s+(?P<name_class>\\w+)\\s*(extends|)\\s*(?P<name_parent>\\w+|\\s*).*'}}
```

Output of `sys.version`:

`'2.6.5 (r265:79096, Mar 19 2010, 18:02:59) [MSC v.1500 64 bit (AMD64)]'`

**Comment by Ultrabenosaurus** [comment]
Although apparently its working now. I restarted Sublime when I originally found that the PHPDox didn't work, and doing so didn't fix it. However now, after having restarted my computer, it seems to be fine.

Not entirely sure why, but sorry for what seems to have been a false alarm.

**Comment by capnfabs** [comment]
I had the same issue after installing from Package Control. Restarting Sublime Text fixed the problem.
